// AI-generated custom elements — the sandboxed runtime. An element is a pure 2D canvas draw-function whose
// BODY is generated by the AI (Phase 2) and stored as a string. It only ever touches the `ctx` + `props`
// we hand it (no window / document / fetch / timers), so a bad element can't reach outside its box. See
// production/AI_ELEMENTS_DESIGN.md.

export interface ElementRenderTheme {
  fg: string;          // primary text / strokes
  bg: string;          // surface behind the element (often transparent on a template)
  accent: string;      // brand accent
  muted: string;       // secondary / gridlines
  positive: string;    // up / gains
  negative: string;    // down / losses
  fontFamily: string;  // brand font (CSS family)
}

export interface ElementRenderProps {
  width: number;       // element box width  (canvas px) — DRAW RELATIVE TO THIS
  height: number;      // element box height (canvas px)
  progress: number;    // 0→1 animation clock (static contexts pass 1 = settled frame)
  data: unknown;       // bound data (from a node) or the element's defaultData
  theme: ElementRenderTheme;
  t: number;           // wall-clock ms for continuous loops (export pins it via progress)
}

// The data-binding contract: a data element declares typed inputs (same shape as automation node ports) so
// nodes can map data in. A static element has an empty schema.
export interface ElementInput {
  key: string;
  label: string;
  dataType: 'number' | 'string' | 'array' | 'object' | 'series' | 'ohlc';
  required?: boolean;
  description?: string;
}

type CompiledFn = (ctx: CanvasRenderingContext2D, props: ElementRenderProps) => void;

// Compile once per unique code string. null = it failed to compile (don't keep retrying).
const cache = new Map<string, CompiledFn | null>();

function compile(code: string): CompiledFn | null {
  if (cache.has(code)) return cache.get(code) ?? null;
  let fn: CompiledFn | null = null;
  try {
    // The AI writes the function BODY; only `ctx` and `props` are in scope.
    fn = new Function('ctx', 'props', '"use strict";\n' + code) as CompiledFn;
  } catch {
    fn = null;
  }
  cache.set(code, fn);
  return fn;
}

/**
 * Draw a custom element into `ctx`. The caller must already have translated `ctx` so (0,0) is the element's
 * top-left and clipped/positioned as needed; the element draws within `props.width` × `props.height`.
 * Always balanced (one save/restore) and never throws — a compile/runtime failure draws an error box.
 */
export function renderCustomElement(ctx: CanvasRenderingContext2D, code: string, props: ElementRenderProps): void {
  const fn = compile(code);
  ctx.save();
  try {
    if (fn) fn(ctx, props);
    else drawError(ctx, props);
  } catch {
    drawError(ctx, props);   // best-effort; any partial draw is acceptable until the Worker sandbox (Phase 5)
  } finally {
    ctx.restore();
  }
}

function drawError(ctx: CanvasRenderingContext2D, props: ElementRenderProps): void {
  const { width: w, height: h } = props;
  ctx.save();
  ctx.strokeStyle = 'rgba(248,113,113,0.9)';
  ctx.setLineDash([6, 4]);
  ctx.lineWidth = 2;
  ctx.strokeRect(1, 1, Math.max(0, w - 2), Math.max(0, h - 2));
  ctx.setLineDash([]);
  ctx.fillStyle = 'rgba(248,113,113,0.9)';
  ctx.font = `${Math.max(11, Math.round(h * 0.08))}px system-ui, sans-serif`;
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText('⚠ element error', w / 2, h / 2);
  ctx.restore();
}
